### ISSUE TITLE
预付单请求返回结果，获取数据新增trade_type判断

### ISSUE THREAD

**Issue by irisggmm** [sheawey/DelzPay#1]
DelzPay/src/Delz/Pay/WeChat/Message/CreateOrderResponse.php
第21行请更新如下
public function getData()
    {
        if (!$this->isSuccessful()) {
            throw new PayException($this->getErrorCode() . ': ' . $this->getErrorMessage());
        }

        if ($this->data['trade_type'] == 'APP') {
            return $this->getAppData();
        }

        if ($this->data['trade_type'] == 'JSAPI') {
            return $this->getJsData();
        }
        if ($this->data['trade_type'] == 'NATIVE') {
            return $this->data;
        }
    }

**Comment by sheawey** [comment]
已增加
